### ISSUE TITLE
Morning Session Peer to Peer Code Review

### ISSUE THREAD

**Issue by DyaryRaoof** [Wikitelmex/Portfolio#5]

**Comment by DyaryRaoof** [comment]
I think it is best to use an `<section>` instead of `<section>` in your code with a class of `"card"` so that it is more semantically approperiate.

**Comment by lfmnovaes** [comment]
One suggestion would be the `<li>` child classes from `<ul>` about-skills should be centered.

**Comment by Wikitelmex** [comment]
tyvm for supporting me with this issue
